# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('a1', models.CharField(max_length=1)),
                ('a2', models.CharField(max_length=1)),
                ('a3', models.CharField(max_length=1)),
                ('a4', models.CharField(max_length=1)),
                ('a5', models.CharField(max_length=1)),
                ('a6', models.CharField(max_length=1)),
                ('a7', models.CharField(max_length=1)),
                ('a8', models.CharField(max_length=1)),
                ('a9', models.CharField(max_length=1)),
                ('a10', models.CharField(max_length=1)),
                ('a11', models.CharField(max_length=1)),
                ('a12', models.CharField(max_length=1)),
                ('a13', models.CharField(max_length=1)),
                ('a14', models.CharField(max_length=1)),
                ('a15', models.CharField(max_length=1)),
                ('a16', models.CharField(max_length=1)),
                ('a17', models.CharField(max_length=1)),
                ('a18', models.CharField(max_length=1)),
                ('a19', models.CharField(max_length=1)),
                ('a20', models.CharField(max_length=1)),
                ('a21', models.CharField(max_length=1)),
                ('a22', models.CharField(max_length=1)),
                ('a23', models.CharField(max_length=1)),
                ('a24', models.CharField(max_length=1)),
                ('a25', models.CharField(max_length=1)),
                ('a26', models.CharField(max_length=1)),
                ('a27', models.CharField(max_length=1)),
                ('a28', models.CharField(max_length=1)),
                ('a29', models.CharField(max_length=1)),
                ('a30', models.CharField(max_length=1)),
                ('a31', models.CharField(max_length=1)),
                ('a32', models.CharField(max_length=1)),
                ('a33', models.CharField(max_length=1)),
                ('a34', models.CharField(max_length=1)),
                ('a35', models.CharField(max_length=1)),
                ('a36', models.CharField(max_length=1)),
                ('a37', models.CharField(max_length=1)),
                ('a38', models.CharField(max_length=1)),
                ('a39', models.CharField(max_length=1)),
                ('a40', models.CharField(max_length=1)),
                ('a41', models.CharField(max_length=1)),
                ('a42', models.CharField(max_length=1)),
                ('a43', models.CharField(max_length=1)),
                ('a44', models.CharField(max_length=1)),
                ('a45', models.CharField(max_length=1)),
                ('a46', models.CharField(max_length=1)),
                ('a47', models.CharField(max_length=1)),
                ('a48', models.CharField(max_length=1)),
                ('a49', models.CharField(max_length=1)),
                ('a50', models.CharField(max_length=1)),
                ('a51', models.CharField(max_length=1)),
                ('a52', models.CharField(max_length=1)),
                ('a53', models.CharField(max_length=1)),
                ('a54', models.CharField(max_length=1)),
                ('a55', models.CharField(max_length=1)),
                ('a56', models.CharField(max_length=1)),
                ('a57', models.CharField(max_length=1)),
                ('a58', models.CharField(max_length=1)),
                ('a59', models.CharField(max_length=1)),
                ('a60', models.CharField(max_length=1)),
                ('a61', models.CharField(max_length=1)),
                ('a62', models.CharField(max_length=1)),
                ('a63', models.CharField(max_length=1)),
                ('a64', models.CharField(max_length=1)),
                ('a65', models.CharField(max_length=1)),
                ('a66', models.CharField(max_length=1)),
                ('a67', models.CharField(max_length=1)),
                ('a68', models.CharField(max_length=1)),
                ('a69', models.CharField(max_length=1)),
                ('a70', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('extraversion', models.FloatField()),
                ('introversion', models.FloatField()),
                ('intuition', models.FloatField()),
                ('sensing', models.FloatField()),
                ('feeling', models.FloatField()),
                ('thinking', models.FloatField()),
                ('percieving', models.FloatField()),
                ('judging', models.FloatField()),
                ('abbrev', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('answer_id', models.ForeignKey(to='master.TestAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='TypeContent',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typ', models.CharField(max_length=4)),
                ('intro', models.TextField()),
                ('intro_p', models.TextField()),
                ('jung_pref', models.TextField()),
                ('strength', models.TextField()),
                ('strength_p', models.TextField()),
                ('weakness', models.TextField()),
                ('weakness_p', models.TextField()),
                ('success', models.TextField()),
                ('s2f', models.TextField()),
                ('pot_prob', models.TextField()),
                ('solns', models.TextField()),
                ('living_happy', models.TextField()),
                ('rules', models.TextField()),
                ('rules_p', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='type_id',
            field=models.ForeignKey(to='master.TypeContent'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user_id',
            field=models.ForeignKey(default=0, to=settings.AUTH_USER_MODEL),
        ),
    ]
